export default [
  {
    OrderID: 10248,
    CustomerID: 'VINET',
    EmployeeID: 5,
    ShipRegion: 'CJ',
    ShipCountry: 'France',
    Verified: !0,
  },
  {
    OrderID: 10249,
    CustomerID: 'TOMSP',
    EmployeeID: 6,
    ShipRegion: 'CJ',
    ShipCountry: 'Germany',
    Verified: !1,
  },
  {
    OrderID: 10250,
    CustomerID: 'HANAR',
    EmployeeID: 4,
    ShipRegion: 'RJ',
    ShipCountry: 'Brazil',
    Verified: !0,
  },
  {
    OrderID: 10251,
    CustomerID: 'VICTE',
    EmployeeID: 3,
    ShipRegion: 'CJ',
    ShipCountry: 'France',
    Verified: !0,
  },
  {
    OrderID: 10252,
    CustomerID: 'SUPRD',
    EmployeeID: 4,
    ShipRegion: 'CJ',
    ShipCountry: 'Belgium',
    Verified: !0,
  },
  {
    OrderID: 10253,
    CustomerID: 'HANAR',
    EmployeeID: 3,
    ShipRegion: 'RJ',
    ShipCountry: 'Brazil',
    Verified: !0,
  },
  {
    OrderID: 10254,
    CustomerID: 'CHOPS',
    EmployeeID: 5,
    ShipRegion: 'CJ',
    ShipCountry: 'Switzerland',
    Verified: !1,
  },
  {
    OrderID: 10255,
    CustomerID: 'RICSU',
    EmployeeID: 9,
    ShipRegion: 'CJ',
    ShipCountry: 'Switzerland',
    Verified: !0,
  },
  {
    OrderID: 10256,
    CustomerID: 'WELLI',
    EmployeeID: 3,
    ShipRegion: 'SP',
    ShipCountry: 'Brazil',
    Verified: !1,
  },
  {
    OrderID: 10257,
    CustomerID: 'HILAA',
    EmployeeID: 4,
    ShipRegion: 'Táchira',
    ShipCountry: 'Venezuela',
    Verified: !0,
  },
  {
    OrderID: 10258,
    CustomerID: 'ERNSH',
    EmployeeID: 1,
    ShipRegion: 'CJ',
    ShipCountry: 'Austria',
    Verified: !0,
  },
  {
    OrderID: 10259,
    CustomerID: 'CENTC',
    EmployeeID: 4,
    ShipRegion: 'CJ',
    ShipCountry: 'Mexico',
    Verified: !1,
  },
  {
    OrderID: 10260,
    CustomerID: 'OTTIK',
    EmployeeID: 4,
    ShipRegion: 'CJ',
    ShipCountry: 'Germany',
    Verified: !0,
  },
  {
    OrderID: 10261,
    CustomerID: 'QUEDE',
    EmployeeID: 4,
    ShipRegion: 'RJ',
    ShipCountry: 'Brazil',
    Verified: !1,
  },
  {
    OrderID: 10262,
    CustomerID: 'RATTC',
    EmployeeID: 8,
    ShipRegion: 'NM',
    ShipCountry: 'USA',
    Verified: !0,
  },
];
